-- Administrator access and mutation history. Safe to run more than once.
create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id text not null,
  actor_name text not null default '관리자',
  action text not null,
  target_type text not null default '',
  target_id text not null default '',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_at_idx
  on public.admin_audit_logs (created_at desc);

create index if not exists admin_audit_logs_actor_created_idx
  on public.admin_audit_logs (actor_id, created_at desc);

alter table public.admin_audit_logs enable row level security;

drop policy if exists "admin_audit_logs_select_admin" on public.admin_audit_logs;
create policy "admin_audit_logs_select_admin"
on public.admin_audit_logs
for select
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid() and profiles.is_admin = true
  )
);

revoke insert, update, delete on public.admin_audit_logs from anon, authenticated;
grant select on public.admin_audit_logs to authenticated;
